version: "3"

services:

  mongodb:
    image: mongo
    ports:
      - "27017"
    volumes:
      - data:/db

  web:
    build: .
    ports:
      - "80:80"
    env_file:
      - ..env-prod



volumes:
  data: